# version: '3.9'

services:
  django-app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    # command: >
    #   sh -c "
    #     until nc -z database 5432;
    #     do
    #       echo 'Esperando a que Postgres esté listo...';
    #       sleep 2;
    #     done;
    #     python manage.py runserver 0.0.0.0:8000
    #   "
    command: >
      sh -c 
        "python manage.py wait_for_db &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=database
      - DB_NAME=dev_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - database
  
  database:
    image: postgres:16-alpine
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


volumes:
  database-data: